import torch
from torch.utils.data import Dataset
import os


class DDPODataset(Dataset):
    def __init__(self, config):
        self.root = config['root_path']
        # We expect a folder of .pt files generated by your preprocessing script
        # Each .pt file should contain dict:
        # {'chosen_latents', 'rejected_latents', 'prompt_embeds', 'pooled_embeds'}
        self.files = [f for f in os.listdir(self.root) if f.endswith('.pt')]

        if len(self.files) == 0:
            raise ValueError(f"No .pt files found in {self.root}. Did you run pre-computation?")

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        data = torch.load(os.path.join(self.root, self.files[idx]), map_location='cpu')
        return {
            "w_latents": data['chosen_latents'].squeeze(0),
            "l_latents": data['rejected_latents'].squeeze(0),
            "prompt_embeds": data['prompt_embeds'].squeeze(0),
            "pooled_embeds": data['pooled_embeds'].squeeze(0)
        }